#! /bin/bash

failed=0

IFS=$(echo -en "\n\b")

for file in $(git diff --cached --diff-filter=d --name-only); do
  diff=$(git show ":$file" | grep -n "DO NOT COMMIT");
  if [[ $? -eq 0 ]]; then
    echo $diff | sed "s|^|$file:|g"
    failed=1
  fi
done

exit $failed
