tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"

cask "android-platform-tools"
# cask "google-chrome"
# cask "iterm2"
# cask "lastpass"
cask "ngrok"
cask "robo-3t"
# cask "slack"
# cask "sublime-text"

brew "asdf"
brew "automake"
brew "openssl@1.1"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "coreutils"
brew "libyaml"
brew "libtiff"
brew "ffmpeg"
brew "findutils"
brew "gawk"
brew "git"
brew "gnu-sed"
brew "gnupg"
brew "grep"
brew "htop"
brew "libtool"
brew "imagemagick"
brew "jq"
brew "libxml2"
brew "libxslt"
brew "lzip"
brew "mysql-client"
brew "netcat"
brew "nginx", restart_service: true
brew "node"
brew "nvm"
brew "pngcheck"
brew "pyenv"
brew "pyenv-virtualenv"
brew "redis"
brew "rename"
brew "scc"
brew "telnet"
brew "tree"
brew "watch"
brew "wget"
brew "yarn"
brew "zlib"
brew "heroku/brew/heroku"
