#! /usr/bin/env bash

set -eu

function find_git_subdirs() {
  for d in `find . -mindepth 1 -maxdepth 1 -type d -exec readlink -f {} + | sort`; do
    ([ -d $d ] && [ -d $d/.git ])|| continue
    echo "$d"
  done
}

cur_dir=`pwd`;
for d in `find_git_subdirs`; do
    cd $cur_dir
    cd $d;
    dir=${d#"$cur_dir/"}
    branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
    printf '********************  %-10s  ********************  %-40s\n' "$branch" "$dir"  1>&2;
    if [ $# -eq 0 ]; then
        LANG=en_US git diff-index --quiet HEAD -- && \
            (git status | grep 'nothing to commit, working tree clean' > /dev/null) && \
            echo -e "No changes\n" && \
            cd ../ && \
            continue;
        LANG=en_US git branch && LANG=en_US git status;
    else
        if [[ $1 == git && $2 == grep ]]; then
            eval "$1 $2 --color=always ${@:3}" | sed "s|^|$(basename $d)/|g";
        else
            eval "$@";
        fi
    fi;
    echo "";
done;
cd $cur_dir
