#! /usr/bin/env bash

set -euo pipefail

git add --intent-to-add .

main_branch=`git symbolic-ref --short refs/remotes/origin/HEAD`
files=`(git diff --name-only $main_branch...HEAD && git diff --name-only HEAD) | sort | uniq`

echo $files | xargs pre-commit run $@ --files
